### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by xurizaemon** [hubot-new/botforge#1]
Per https://github.com/hubotio/hubot/issues/1541 discussion, a zero-effort name was chosen to kick off.

This is the issue where we determine a better name for the organisation and repo.

**Comment by xurizaemon** [comment]
@joeyguerra I propose we remove the name change on the repo (so this becomes hubot-new/hubot). OK if I do that proactively?

We can always change the name for the repo later, but I suspect the repo name and things like `./bin/hubot` should be kept in alignment until we have a plan.

**Comment by joeyguerra** [comment]
That sounds good. I was thinking it would be less confusing if the repo name was different, but to be frank, we don't know yet. So it makes sense to keep the repo name the same.

**Comment by mistydemeo** [comment]
I don't work at GitHub anymore so I'm not speaking in any official capacity, but as far as I know "Hubot" is a trademarked term. If you're planning on maintaining this as a fork, I think it'd be good to come up with a fun distinctive name.

**Comment by joh6nn** [comment]
> I don't work at GitHub anymore so I'm not speaking in any official capacity, but as far as I know "Hubot" is a trademarked term.

Thanks for the heads-up! I've confirmed that here: https://trademarks.justia.com/872/82/hubot-87282998.html : Github have trademarked the name, so we'll have to come up with something else. All of the things I immediately thought of below are already in use somewhere:

- newbot
- nubot
- youbot
- iubot
- nodebot
- jsbot
- Flexo (this one was my favorite :slightly_frowning_face:)

maybe HughBot? :wink: Doesn't seem to be in active use!

**Comment by xurizaemon** [comment]
Naming is hard, I'm thinking about criteria that make a name good or bad to help.

- **Existing criteria** - we're building on existing efforts here. Criteria from [CONTRIBUTING.md](https://github.com/hubot-new/hubot/blob/master/CONTRIBUTING.md) and [Contributor Covenant](https://www.contributor-covenant.org/) apply, along with the existing MIT license. 
- **Copyright** - for project sustainability, we shouldn't choose a name which is copyrighted (domains are relevant here, I have no expertise but we can look at those referenced in [Hubot's copyrighting](https://trademarks.justia.com/872/82/hubot-87282998.html))
- **Inclusivity** - for project viability, we should choose a name which doesn't excluding people. Examples here would be names which are offensive or culturally insensitive. For me this also means the name shouldn't reinforce existing stereotypes (eg reinforcing assistant/gender role expectations).
- **Identity** - for project adoption (and effective naming), we should choose a name which is sufficiently unique. This may also want to recognise the heritage of the work we're building on.
- **Purpose/application** - this project is a platform for making bots, which uses the platform name as the default bot name. Is that still correct?

Those are some things popped into my head so far!

**Comment by xurizaemon** [comment]
A name suggestion! **ChatSaw**

My initial ideas were plays on the Hubot name too, but I now think that we don't really want a name that's too similar?

I was cutting some shelves today and reflecting on how effective a good saw is (a coping saw in this case), and thought of how bots can slice and dice through the intersection of chat and integrated systems.

**Comment by joh6nn** [comment]
I like ChatSaw! Your comments about slicing and dicing made me think of a knife, though, and I came up with this extremely quick and dirty logo mockup for the name "ChatKnife": 
![chatknife-mockup](https://user-images.githubusercontent.com/1129329/230914096-7656a6b2-6bc0-4264-ac37-cdaf0bbdab2c.png). For a final product, I think I'd make the chat bubble thinner so it's more like the actual handle of the knife, maybe put "ChatKnife" in the bubble, etc. 

If no one else likes it, I'm prepared to go with ChatSaw :slightly_smiling_face:

**Comment by joeyguerra** [comment]
ChatSaw doesn't resonate with me, but your framing (tooling) and criteria listed above does.

I used ChatGPT for some ideas. Here's a list of more options:

* BotForge - short, memorable, and evokes the idea of a tool for creating and customizing chat bots, which aligns well with the extensible nature of Hubot
* ForgeChat - incorporates the idea of a tool for creating and building
* CraftBot: This name combines the idea of crafting and building with the word "bot", which is a common term for chat bots.
* BuildAI: This name plays off the word "AI" (artificial intelligence) and emphasizes the idea of building or constructing.
* Formulate: This name implies the idea of creating or formulating something, and could work well for a chat bot that helps users solve problems or generate ideas.
* ShapeShift: This name incorporates the idea of transformation and change, which could work well for a chat bot that adapts to different contexts or environments.
* Constructo: This name incorporates the Latin word for "build" (constructus) and has a playful, almost whimsical ring to it.
* CurioBot - Wall-E inspired
* ExplorerBot - Wall-E inspired
* LearnBot: This name emphasizes the idea of learning and growth, which are key themes in the movie.
* EmotiBot: This name highlights the emotional intelligence and empathy that Number 5 develops over the course of the movie.
* ConnectBot: This name emphasizes the idea of building connections and relationships, which are important to Number 5's character development.
* ThinkerBot: This name plays off the idea of Number 5's increased cognitive abilities and his newfound ability to think for himself.
* CuriousBot: This name reflects Number 5's insatiable curiosity and desire to learn more about the world around him.
* EmoBot: This name plays off the idea of emotional intelligence, which is a key trait of Chappie's character.
* IndividualBot: This name emphasizes the idea of individuality and uniqueness, which are important themes in the movie.
* ConsciousBot: This name reflects Chappie's increasing awareness of his own existence and his ability to think and make decisions for himself.
* AdaptBot: This name plays off the idea of Chappie's adaptability and his ability to learn and evolve over time.
* FreedomBot: This name reflects Chappie's desire for freedom and independence, which drives much of the movie's plot.
* ChampBot
* SteelBot
* BondBot
* InspireBot
* MaverickBot

None of these stood out to me, but I like the ideas related to forge, curiosity, construction and maverick.

🤔

**Comment by joeyguerra** [comment]
how 'bout qbert?

**Comment by joeyguerra** [comment]
or hubert?

**Comment by joeyguerra** [comment]
or h21bot?

**Comment by joh6nn** [comment]
actually, now that we have access to the original project, is this project still necessary?

**Comment by joeyguerra** [comment]
I haven't heard from Josh (Hubotio org owner) in a few weeks. So I was thinking of moving forward with the initial plan to fork  because I can't get my PRs approved and merged in a timely fashion. I'm assuming that Josh (and others) are busy and no longer really interested in the project.

**Comment by joh6nn** [comment]
In that case, my current picks, in order:

1. BotForge
2. ChatKnife
3. ChatSaw

**Comment by joeyguerra** [comment]
I like botforge.

**Comment by joeyguerra** [comment]
Ok. I'm creating a PR for the name change to `botforge`. 

Any opinions about what to name the organization? I want to also create an org on NPM so that we can `npm install @neworgname/botforge`.
