### ISSUE TITLE
Rename default branch to `main`

### ISSUE THREAD

**Issue by joeyguerra** [hubot-new/botforge#38]

**Comment by joh6nn** [comment]
I spent the last decade doing devops type stuff, so I tend to favor "dev", "test", "prod" style branch names. Would you be ok with something like that?

**Comment by joeyguerra** [comment]
I've been practicing trunk based development for years and don't want to go back to managing multiple branches. However, if there's problems or user needs that managing multiple long lived branches, I would definitely be opened to it.

The intent of this issue was just to align with the naming standard that Github implemented, `master` to `main`.

**Comment by xurizaemon** [comment]
Thanks for putting this forward - yes.

**Comment by xurizaemon** [comment]
- [ ] Update branch references in `.github/workflows/*`
- [ ] Update README.md, CONTRIBUTING.md, docs/deploying/* references
- [ ] Update `release` (is that used/can it be removed?)

**Comment by joeyguerra** [comment]
Did this today.
